"use client";
import { useState } from "react";
import type { MOMResult } from "@/types";

interface Props {
  result: MOMResult;
}

export default function EmailExport({ result }: Props) {
  const [copied, setCopied] = useState(false);

  function buildEmailBody(): string {
    const date = new Date().toLocaleDateString("en-US", {
      weekday: "long",
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    const lines: string[] = [
      `Hi,`,
      ``,
      `Please find the Minutes of Meeting below for our meeting on ${date}.`,
      ``,
      `${"─".repeat(60)}`,
      ``,
    ];

    if (result.summary) {
      lines.push(`SUMMARY`);
      lines.push(result.summary);
      lines.push(``);
    }

    if (result.actions.length) {
      lines.push(`ACTION ITEMS`);
      result.actions.forEach((a) => lines.push(`  • ${a}`));
      lines.push(``);
    }

    if (result.decisions.length) {
      lines.push(`KEY DECISIONS`);
      result.decisions.forEach((d, i) => lines.push(`  ${i + 1}. ${d}`));
      lines.push(``);
    }

    if (result.attendees.length) {
      lines.push(`ATTENDEES`);
      lines.push(`  ${result.attendees.join(", ")}`);
      lines.push(``);
    }

    if (result.unansweredQuestions.length) {
      lines.push(`OPEN QUESTIONS`);
      result.unansweredQuestions.forEach((q) =>
        lines.push(`  • ${q.question}`),
      );
      lines.push(``);
    }

    lines.push(`${"─".repeat(60)}`);
    lines.push(`Generated by MeetMind AI`);

    return lines.join("\n");
  }

  function openEmail() {
    const subject = encodeURIComponent(
      `Minutes of Meeting — ${new Date().toLocaleDateString("en-US", {
        month: "long",
        day: "numeric",
        year: "numeric",
      })}`,
    );
    const body = encodeURIComponent(buildEmailBody());
    const mailtoUrl = `mailto:?subject=${subject}&body=${body}`;

    if (mailtoUrl.length < 2000) {
      const link = document.createElement("a");
      link.href = mailtoUrl;
      link.click();
    } else {
      navigator.clipboard.writeText(buildEmailBody()).then(() => {
        setCopied(true);
        setTimeout(() => setCopied(false), 3000);
      });
    }
  }

  return (
    <button
      onClick={openEmail}
      className="flex items-center gap-1.5 px-4 py-2 rounded-lg text-[11px] font-mono text-white/40 hover:text-white/70 transition-all duration-200"
      style={{
        background: "rgba(255,255,255,0.04)",
        border: "1px solid rgba(255,255,255,0.08)",
      }}
    >
      {copied ? "✓ Copied to clipboard" : "✉ Email"}
    </button>
  );
}
